language: python

matrix:
    include:
        - python: 2.7
          env: TOXENV=27
        - python: 3.5
          env: TOXENV=35
        - python: 3.6
          env: TOXENV=36
        - python: pypy
          env: TOXENV=pypy
        - python: pypy3
          env: TOXENV=pypy3

before_install:
  - cd $HOME
  - mkdir bin
  - export PATH=$HOME/bin:$PATH
  - "if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then deactivate && wget https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-5.8-linux_x86_64-portable.tar.bz2 && tar -jxvf pypy-5.8-linux_x86_64-portable.tar.bz2 && echo 'Setting up aliases...' && cd pypy-5.8-linux_x86_64-portable/bin/ && export PATH=$PWD:$PATH && ln -s pypy python && echo 'Setting up pip...' && ./pypy -m ensurepip ; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then deactivate && wget https://bitbucket.org/squeaky/portable-pypy/downloads/pypy3.5-5.8-beta-linux_x86_64-portable.tar.bz2 && tar -jxvf pypy3.5-5.8-beta-linux_x86_64-portable.tar.bz2 && echo 'Setting up aliases...' && cd pypy3.5-5.8-beta-linux_x86_64-portable/bin/ && export PATH=$PWD:$PATH && ln -s pypy3 python && echo 'Setting up pip...' && ./pypy3 -m ensurepip && ln -s pip3 pip ; fi"
  - cd $TRAVIS_BUILD_DIR

install:
  - pip install tox codecov

script: tox

after_success:
  - codecov
